CREATE TABLE orders (
    order_id INT AUTO_INCREMENT PRIMARY KEY,
    user_name VARCHAR(255) NOT NULL DEFAULT 1,
    user_id VARCHAR(255) NOT NULL DEFAULT 1,
    user_email VARCHAR(255) NOT NULL DEFAULT 1,
    user_mobile VARCHAR(15) NOT NULL DEFAULT 1,
    user_address VARCHAR(255) NOT NULL DEFAULT 1,
    user_payment_id VARCHAR(20) NOT NULL DEFAULT 1,
    order_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    product_details JSON NOT NULL DEFAULT 1,
    total_amount DECIMAL(10, 2) NOT NULL DEFAULT 1,
    status VARCHAR(50) DEFAULT 'Pending' NOT NULL
);